# Generated by Django 3.2.20 on 2023-07-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lessonarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonarticle',
            options={'verbose_name': 'lesson_article', 'verbose_name_plural': 'lesson_articles'},
        ),
        migrations.AlterModelTable(
            name='lessonarticle',
            table='lesson_article',
        ),
    ]
