# Generated by Django 3.2.20 on 2023-08-22 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230712_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excercise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'db_table': 'excercise',
            },
        ),
        migrations.CreateModel(
            name='ExcerciseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excercise_article', to=settings.AUTH_USER_MODEL)),
                ('excercises', models.ManyToManyField(to='core.Excercise')),
            ],
            options={
                'verbose_name': 'exercise_article',
                'verbose_name_plural': 'exercise_articles',
                'db_table': 'excercise_article',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tag',
            },
        ),
        migrations.DeleteModel(
            name='LessonArticle',
        ),
        migrations.AddField(
            model_name='excercisearticle',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
