# Generated by Django 3.2.20 on 2023-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230830_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='explanation_solution',
            field=models.TextField(default=None, help_text='Text to explain problem-solution structures', null=True),
        ),
    ]
