# Generated by Django 3.2.20 on 2023-08-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_excercise_explanation_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercisearticle',
            name='excercises',
            field=models.ManyToManyField(blank=True, to='core.Excercise'),
        ),
    ]
