# Generated by Django 3.2.20 on 2023-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_excercisearticle_excercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='explanation_solution',
            field=models.TextField(blank=True, default=None, help_text='Text to explain problem-solution structures', null=True),
        ),
    ]
