# Generated by Django 3.2.20 on 2023-08-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_excercise_explanation_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Use this excercise as sample exercise in the article'),
        ),
    ]
